openapi: 3.0.0
info:
  title: API de Autenticação
  description: API para cadastro, login e verificação de tokens
  version: "1.0.0"

servers:
  - url: http://localhost:3333/api

paths:
  /auth/register:
    post:
      summary: Registra um novo usuário (requer autenticação de admin)
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        "201":
          description: Usuário registrado com sucesso
        "401":
          description: Token de autenticação inválido ou ausente
        "403":
          description: Acesso negado - requer papel de administrador
          
  /auth/login:
    post:
      summary: Realiza login de usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginCredentials'
      responses:
        "200":
          description: Login realizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  token:
                    type: string
                    description: Token JWT para autenticação
        "401":
          description: Credenciais inválidas
    /users:
    get:
      summary: Retorna lista de usuários (requer autenticação de admin)
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Lista de usuários retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        "401":
          description: Token de autenticação inválido ou ausente
        "403":
          description: Acesso negado - requer papel de administrador

components:
  schemas:
    UserInput:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
        email:
          type: string        
        password:
          type: string
    
    UserLoginCredentials:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
    
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        createdAt:
          type: string
          format: date-time

  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
